### ISSUE TITLE
Add C# version of Ray Tracing in One Weekend to Wiki

### ISSUE THREAD

**Issue by ronnieholm** [RayTracing/raytracinginoneweekend#59]
I put my C#/.NET Core implementation of Ray Tracing in One Weekend on GitHub:

https://github.com/ronnieholm/Ray-tracing-in-one-weekend-CSharp

Perhaps worth adding to Wiki -> Implementations in Other Languages.

**Comment by hollasch** [comment]
Done — thanks Ronnie!
