### ISSUE TITLE
Chapter 7, color function: help needed

### ISSUE THREAD

**Issue by Fahisto** [RayTracing/raytracinginoneweekend#60]
Code inside color function is rather confusing. Specifically, the following part:
```
if (world->hit(r, 0.0, MAXFLOAT, rec)) 
{
    vec3 target = rec.p + rec.normal + random_in_unit_sphere();
}
```
Shouldn't there be a "return" statement at least? Without it, code doesn't make sense to me and it doesn't compile. When I return ```target``` variable, result looks like this:
![my_ppm](https://user-images.githubusercontent.com/45635704/62087849-de293c80-b26b-11e9-8849-c5a3aebde5c6.png)
Images from previous chapters were fine. Maybe I'm missing something?

**Comment by hollasch** [comment]
You'll need to provide more information. The color function has different implementations depending on where you are in the book, or if you're using the final form source code. I can't find any version that matches the few lines you've given above.

**Comment by Fahisto** [comment]
I'm currently at chapter 7, and I basically copied function implementation from the book, not from the source code:
```
vec3 color(const ray& r, hitable *world, int depth) {
    hit_record rec;
    if (world->hit(r, 0.0, MAXFLOAT, rec)) {
        vec3 target = rec.p + rec.normal + random_in_unit_sphere();
    }
    else {
        vec3 unit_direction = unit_vector(r.direction());
        float t = 0.5*(unit_direction.y() + 1.0);
        return (1.0-t)*vec3(1.0, 1.0, 1.0) + t*vec3(0.5, 0.7, 1.0);
    }
}
```

**Comment by hollasch** [comment]
Interesting. The web version (currently under development) lacks a line in the code block. Are you using the content in the `docs` directory? That's not ready yet. It looks like both the Kindle version and the official PDF version have the correct code (see the [release page](https://github.com/RayTracing/raytracinginoneweekend/releases) for the latest official release).

I'll fix up the code in the developing book as well.

**Comment by hollasch** [comment]
Fixed in work-in-progress book.

**Comment by trevortheblack** [comment]
Might be prudent to add a line to the readme specifying that readers should
wait a week or two for the docs,

And then redirect to the realtimerendering pdf

**Comment by hollasch** [comment]
Yeah, I think you're right. I've added a warning banner to each page. Working on other two books now...

**Comment by hollasch** [comment]
@Fahisto — let me know if this resolves your issue so I can close this.

**Comment by Fahisto** [comment]
Everything works now, thank you for help!
